### model
model_name_or_path: /data/public_checkpoints/huggingface_models/Llama3.1-8B-Instruct
trust_remote_code: true
add_special_tokens: <think>,</think>
max_length: 8192

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: CogFlow_files/ds_z3_config.json 

### dataset
dataset: cog_flow_distillr1
template: llama3
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/Llama3.1-8b/full/sft_distillr1
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: false

report_to: tensorboard
run_name: CogFlow_SFT_llama3.1-8b-instruct_distillr1

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 25
